baseURL: https://lujiayuan77.github.io/
languageCode : en-us
title : lujiayuan
theme : PaperMod
# publishDir : docs
enableEmoji : true

params:

  homeInfoParams:
    Title: Hello
    Content: welcome to my blog
menu:
  main:
    - name: 全部
      url: archives/
      weight: 5
    - name: 搜索
      url: search/
      weight: 10
    - name: 标签
      url: /tags/
      weight: 10


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary